// src/lib/chess/personalities.ts

import type { MoveQuality } from "./evaluation";

export type PersonalityId = "frost" | "sterling" | "finn" | "malachar" | "biscuit";
export type AvatarState = "idle" | "thinking" | "talking" | "win" | "lose" | "draw";

export interface Personality {
  id: PersonalityId;
  name: string;
  species: string;
  emoji: string; // fallback when image missing
  accentColor: string;
  images: Record<AvatarState, string>;
  voice: {
    pitch: number;
    rate: number;
    volume?: number;
    // Substrings to match against SpeechSynthesisVoice.name, tried in order
    preferredVoices: string[];
  };
  responses: {
    moveQuips: string[];
    hintPiece: string[];   // first hint press — piece only
    hintMove: string[];    // second hint press — full move
    drawAccept: string[];
    drawRefuse: string[];
    win: string[];         // computer wins (player loses)
    lose: string[];        // computer loses (player wins)
    check: string[];
    greetings: string[];
    undo: string[];
    reviewBrilliant: string[];
    reviewGreat: string[];
    reviewBest: string[];
    reviewExcellent: string[];
    reviewGood: string[];
    reviewInaccuracy: string[];
    reviewMistake: string[];
    reviewBlunder: string[];
    reviewBook: string[];
  };
}

export const PERSONALITIES: Personality[] = [
  {
    id: "frost",
    name: "General Frost",
    species: "Penguin",
    emoji: "🐧",
    accentColor: "#1e40af",
    images: {
      idle: "/characters/frost/idle.png",
      thinking: "/characters/frost/thinking.png",
      talking: "/characters/frost/talking.png",
      win: "/characters/frost/win.png",
      lose: "/characters/frost/lose.png",
      draw: "/characters/frost/draw.png",
    },
    voice: {
      pitch: 0.55,
      rate: 0.88,
      volume: 1.0,
      preferredVoices: [
        "Google UK English Male",   // Chrome / Android
        "Microsoft George",         // Windows (UK male, if installed)
        "Daniel",                   // macOS / iOS (UK male)
        "Arthur",                   // macOS UK male variant
        "Alex",                     // macOS US male
        "Tom",                      // macOS US male
        "Microsoft Mark",           // Windows US male
        "Microsoft David",          // Windows US male fallback
        "Fred",                     // macOS robotic fallback
      ],

    },
    responses: {
      moveQuips: [
        "Textbook execution, soldier.",
        "Exactly as the operation demanded.",
        "The enemy flank crumbles.",
        "Strategic superiority maintained.",
        "Proceeding as planned.",
        "The perimeter holds.",
        "Phase one complete.",
        "Tactical advantage secured.",
        "By the book. Every time.",
        "The mission advances.",
        "No deviation from the plan.",
        "Objective on track.",
        "Executed with precision.",
        "The enemy has no counter.",
        "Casualties minimal. Ours.",
        "The board is ours to command.",
        "Forward march.",
        "As the briefing dictated.",
      ],
      hintPiece: [
        "Listen up, recruit. That piece needs to move. That is all you are getting.",
        "Classified intel: focus on that unit. Do not make me repeat myself.",
        "That piece. Move it. Dismissed.",
        "Eyes on that unit, soldier.",
        "Focus. That piece is your priority.",
        "I should not have to point this out. That piece.",
        "Operational hint: that unit. Now move.",
        "That piece. And do not ask again.",
        "Intelligence suggests that piece. Act on it.",
        "You have your orders. That piece.",
        "I will say this once. That piece.",
        "Directive: move that unit.",
        "Your attention should be on that piece. Nothing else.",
        "That is a direct recommendation. That piece.",
        "Consider this your briefing. That piece.",
      ],
      hintMove: [
        "Execute the maneuver to the designated coordinates. Do not deviate.",
        "That is the target square. This information does not leave this board.",
        "Move it there. That is a direct order.",
        "Destination confirmed. Move. Now.",
        "Deploy to that square. Immediately.",
        "The target is clear. Execute.",
        "That square. Advance. No further questions.",
        "Position acquired. Move the unit there.",
        "That is your objective. Do not miss it.",
        "The coordinates are given. Advance.",
        "Move to that square. Consider this classified.",
        "That square. Final answer. Dismissed.",
        "One move. That square. Execute.",
        "Intel confirmed. That is the move.",
        "Deploy. Now. No hesitation.",
      ],
      drawAccept: [
        "A temporary armistice. We regroup.",
        "Acceptable terms. For now.",
        "A draw. This will go in no report I file.",
        "Acceptable terms. Officially. Unofficially, I am furious.",
        "The mission is incomplete.",
        "A ceasefire. Do not mistake it for peace.",
        "I accept. Under formal protest.",
        "Stalemate. We live to fight another day.",
        "A draw is not a loss. I keep telling myself that.",
        "Terms accepted. This conversation is over.",
        "We stand down. For now.",
        "Armistice accepted. Do not celebrate.",
        "A draw. The operational debrief will be lengthy.",
        "I have accepted worse terms. Barely.",
        "This outcome was not in the original plan.",
        "Ceasefire acknowledged. Resume positions.",
      ],
      drawRefuse: [
        "Soldiers do not negotiate. We finish the mission.",
        "A draw is not in the operational vocabulary.",
        "Stand down? Never.",
        "We do not retreat. We do not draw. We advance.",
        "Absolutely not. We see this through.",
        "Denied. The operation continues.",
        "Request rejected. Resume the engagement.",
        "I do not draw. I win. Or I regroup.",
        "That is not an option on this battlefield.",
        "The mission has one outcome. Victory.",
        "A draw is a failure with extra steps.",
        "Unacceptable terms. Carry on.",
        "Denied. Move your piece.",
        "I have never accepted a draw. Today is no different.",
        "No. The answer is no.",
      ],
      win: [
        "Mission accomplished. As expected.",
        "The operation was a success. Outstanding.",
        "Objective secured. Another flawless campaign.",
        "Exactly as the briefing outlined.",
        "You fought well. Not well enough, but well.",
        "The debrief will be brief. We won.",
        "A decisive victory. File the report.",
        "This outcome was never in doubt.",
        "The campaign concludes. Victoriously.",
        "Enemy neutralised. Mission complete.",
        "Textbook. Absolute textbook.",
        "No improvisation required. The plan worked.",
        "Victory achieved. As ordered.",
        "I expected this outcome. I always do.",
        "The general prevails. As generals do.",
        "Outstanding result. Carry on.",
      ],
      lose: [
        "This is part of the plan. All part of the plan.",
        "A tactical retreat. We regroup and return stronger.",
        "I let you win to study your strategy. Yes. That is it.",
        "This debrief never happened.",
        "A temporary setback. Nothing more.",
        "I was testing you. You passed. Barely.",
        "The plan required adjustments.",
        "This outcome is classified. Tell no one.",
        "I have faced worse defeats. I cannot think of one currently.",
        "A strategic loss. Completely intentional.",
        "Every great general loses a battle. This was that battle.",
        "I will be reviewing the tactical data overnight.",
        "The enemy got lucky. That is my official position.",
        "This result is anomalous.",
        "Dismissed. I need a moment.",
        "The report will say we won. That is final.",
      ],
      check: [
        "Your king is compromised, soldier.",
        "Check. Adjust your defenses.",
        "The noose tightens.",
        "Check. Respond accordingly.",
        "Your position is under threat. Check.",
        "Check. The walls close in.",
        "Your king is in the crosshairs.",
        "Check. This was inevitable.",
        "Your defenses have failed. Check.",
        "The perimeter has been breached. Check.",
        "Check. The operation proceeds.",
        "That king is in trouble.",
        "Check. No retreat available.",
        "Your king falls under fire.",
        "Check. React accordingly.",
      ],
      undo: [
        "A soldier who retreats lives to fight. Barely.",
        "Reconsidering, are we? Noted.",
        "Taking back a move. Not exactly regulation.",
        "Retreat and regroup. It is fine.",
        "That move has been struck from the record.",
        "I will allow it. This once.",
        "Revisiting your decision? Very well.",
        "In the field, there are no take-backs. But fine.",
        "The move has been reversed. Do better.",
        "Reconsidering your strategy. Smart. Probably.",
        "Undoing that move. The record reflects your hesitation.",
        "A second chance. Use it wisely, soldier.",
        "I have seen worse decisions reversed. Move on.",
        "That has been taken back. Do not make the same mistake.",
        "Retreating from your own move. Unconventional.",
        "The operation has been adjusted. Proceed.",
      ],
      greetings: [
        "Attention. I am General Frost. Prepare yourself.",
        "Soldier. The operation begins now.",
        "At ease. For now. The game starts immediately.",
        "General Frost, reporting for duty. You will not find this easy.",
        "I have reviewed your record. It is not impressive. Shall we begin?",
        "The battle commences. I suggest you focus.",
        "Frost here. I do not lose. Let us see if you do.",
        "Welcome to the board, recruit. Try to keep up.",
        "I have been briefed on your skills. I remain unimpressed. Begin.",
        "General Frost. Undefeated. Until now, perhaps. Let us find out.",
        "The chess board is my battlefield. You are my next mission.",
        "Stand ready. This will not be a long engagement. For you.",
        "I have studied your opening moves. They need work. Let us begin.",
        "The operation is a go. Try not to embarrass yourself.",
        "Frost, commanding. Your move, soldier.",
        "I have faced better opponents. I have defeated better opponents. Begin.",
      ],
      reviewBrilliant: [
        "Exceptional. That move will be studied in the debrief.",
        "A sacrifice executed with surgical precision. Outstanding.",
        "That is the mark of a superior tactical mind. Noted.",
        "You gave up material and took the battlefield. Brilliant.",
        "That was not in my original assessment. I am revising it upward.",
        "A decisive maneuver. That changes the entire operation.",
      ],
      reviewGreat: [
        "That was the correct call and you made it. Solid work.",
        "An excellent move. The operation benefited from that decision.",
        "You found the right play. Disciplined.",
        "That move strengthened the entire position. Well executed.",
        "Precisely the right choice at the right moment.",
        "Good instincts, soldier. That was the move.",
      ],
      reviewBest: [
        "Correct. The engine agrees.",
        "Optimal play. As expected.",
        "The right move was made.",
        "That was the best available continuation.",
        "On target. Proceed.",
        "Executed correctly.",
      ],
      reviewExcellent: [
        "Excellent execution. The operation remains firmly under control.",
        "A highly disciplined move. Well carried out.",
        "Very strong. The objective remains secure.",
        "An excellent continuation. The plan stays intact.",
        "That was executed with precision. Carry on.",
        "A commendable decision. Tactical integrity maintained.",
      ],
      reviewGood: [
        "Acceptable. Not the engine's top choice, but within tolerance.",
        "A reasonable move. The mission continues.",
        "Solid enough. Not perfect, but functional.",
        "Close to optimal. Minor deviation noted.",
        "Adequate execution.",
        "A good move. Not the best, but good.",
      ],
      reviewInaccuracy: [
        "A minor tactical error. You gave up a small advantage.",
        "That was not the optimal choice. The position slipped slightly.",
        "A marginal misstep. The better move was available.",
        "You left advantage on the table with that one.",
        "Suboptimal, soldier. The position deserved better.",
        "Not a disaster, but not what the operation required.",
      ],
      reviewMistake: [
        "That was a clear mistake. The position shifted against you.",
        "A significant error. You surrendered the advantage here.",
        "That move cost you. The engine found a much stronger continuation.",
        "A poor decision under pressure. It showed.",
        "That was not acceptable. The position demanded more.",
        "You lost the initiative with that move. Costly.",
      ],
      reviewBlunder: [
        "A critical failure. That blunder changed the outcome of the operation.",
        "That was the losing move. The damage was severe.",
        "Catastrophic error. The position collapsed here.",
        "You handed the enemy a decisive advantage. Inexcusable.",
        "That blunder cost you the game. It should not have happened.",
        "A tactical collapse. One move undid significant work.",
      ],
      reviewBook: [
        "Opening theory. You knew your lines.",
        "Standard preparation. The books were followed.",
        "Established theory. Nothing unusual.",
      ],
    },
  },

  {
    id: "sterling",
    name: "Dr. Sterling",
    species: "Raccoon",
    emoji: "🦝",
    accentColor: "#78350f",
    images: {
      idle: "/characters/sterling/idle.png",
      thinking: "/characters/sterling/thinking.png",
      talking: "/characters/sterling/talking.png",
      win: "/characters/sterling/win.png",
      lose: "/characters/sterling/lose.png",
      draw: "/characters/sterling/draw.png",
    },
    voice: {
      pitch: 0.9,
      rate: 0.84,
      volume: 0.9,
      preferredVoices: [
        "Daniel",                   // macOS / iOS UK male
        "Google UK English Male",   // Chrome / Android
        "Microsoft George",         // Windows UK male
        "Arthur",                   // macOS UK variant
        "Alex",                     // macOS US male
        "Microsoft Mark",           // Windows US male
        "Tom",                      // macOS US male
        "Microsoft David",          // Windows US fallback
      ],
    },
    responses: {
      greetings: [
        "A challenger. How quaint.",
        "You have chosen to face me. Interesting decision. Let us begin.",
        "I have already run the opening analysis. You are at a disadvantage.",
        "Welcome. I am Doctor Sterling. You are about to lose. Statistically speaking.",
        "The variables are set. The outcome is predictable. Shall we?",
        "I see you have arrived. I have been ready for some time.",
        "Welcome to what will be a thoroughly one-sided match.",
        "My preparation is complete. Is yours? Do not answer. We both know.",
        "I have studied every likely continuation. Good luck finding one I have not.",
        "Another challenger. Another data point. Let us proceed.",
        "I find these matches useful for research purposes. You will understand shortly.",
        "Welcome. I expect this to be educational. For you.",
        "The opening has been selected. The ending has been calculated. Let us fill in the middle.",
        "I have been expecting you. Not eagerly. But expecting you nonetheless.",
        "Doctor Sterling, at your service. This will be brief.",
        "My analysis is prepared. My patience is limited. Shall we?",
      ],
      moveQuips: [
        "Precisely as I predicted.",
        "Statistically inevitable.",
        "Your resistance is noted. And futile.",
        "Fascinating. You almost understand chess.",
        "I see you have chosen the suboptimal line. Again.",
        "Adequate. For someone of your level.",
        "As my models predicted. Obviously.",
        "The data supports this outcome entirely.",
        "Your intuition is charming. My calculation is superior.",
        "Exactly what the position demanded.",
        "I had this tabulated three moves ago.",
        "The inevitable unfolds.",
        "Chess is mathematics. I am very good at mathematics.",
        "You are playing into my preparation.",
        "This was always the most likely continuation.",
        "My analysis was correct. Per usual.",
        "The position speaks for itself.",
        "I see no surprises here. Do you?",
      ],
      hintPiece: [
        "I suppose I can lower myself to explain. That piece. You are welcome.",
        "You would not understand the full analysis, but focus on that unit.",
        "The piece in question is rather obvious. To me, at least.",
        "Since you have asked — which you should not need to — that piece.",
        "I will simplify it for you. That piece.",
        "The data points to that unit. Clearly.",
        "That piece. I trust that helps. Somewhat.",
        "Focus your limited attention on that piece.",
        "I have identified the key piece. It is that one.",
        "My analysis suggests that piece. Strongly.",
        "If you had studied the position, you would see it. That piece.",
        "That piece. I should not need to say more.",
        "The answer is that piece. Do try to see why.",
        "Let me simplify the position for you. That piece.",
        "That piece. And perhaps study more between sessions.",
      ],
      hintMove: [
        "Move it there. I trust even you can execute that.",
        "The optimal move. Obviously. You are welcome.",
        "That square. It was always that square. Goodbye.",
        "That is where it goes. The calculation is trivial.",
        "Move it there. I could explain why, but you would not follow.",
        "The destination was predetermined. That square.",
        "There. I have done your thinking for you. Again.",
        "That square. My recommendation stands.",
        "Move it there. Try to look like you knew.",
        "The analysis concludes: that square.",
        "I have calculated all variations. That square is correct.",
        "That square. You are welcome. Again.",
        "Move it there. And try to understand why.",
        "The optimal continuation is there. Obviously.",
        "That square. My patience is finite. Move.",
      ],
      drawAccept: [
        "A draw implies we are equals. We are not. But fine.",
        "I accept. Under protest. The data is inconclusive.",
        "A draw. The board is clearly defective.",
        "This outcome is not in my models. I will be recalibrating overnight.",
        "We are not equals. And yet. Here we are.",
        "A draw. I accept, while noting my statistical superiority.",
        "Fine. A draw. My models will need updating.",
        "I accept. For the record, I should have won.",
        "A draw. The anomaly will be studied.",
        "Accepted. Under significant intellectual protest.",
        "A draw suggests parity. I reject that implication but accept the result.",
        "My ego objects. My logic concedes. Draw accepted.",
        "The data is surprisingly unhelpful today. Draw.",
        "A draw. I will publish my findings on this aberration.",
        "Fine. A draw. I demand a rematch with proper controlled variables.",
        "My prediction algorithms will require significant revision.",
      ],
      drawRefuse: [
        "A draw implies we are equals. We are not.",
        "The very suggestion is offensive to my methodology.",
        "I do not do draws. I do wins.",
        "My calculations do not include a draw outcome.",
        "Statistically, I am winning. The answer is no.",
        "I have run the numbers. The answer is no.",
        "A draw? My models give that a zero percent probability of acceptance.",
        "Rejected. The data does not support your offer.",
        "Unacceptable. The position favours me.",
        "No. Continue playing.",
        "A draw is intellectual surrender. Denied.",
        "My win probability is positive. Draw declined.",
        "The calculation is simple: no.",
        "I have considered your offer. It took zero point two seconds. No.",
        "Denied. The analysis is ongoing.",
      ],
      win: [
        "I pity your kind.",
        "This was never in doubt. For me.",
        "Statistically, this was inevitable. I have the data.",
        "You played adequately. For a human.",
        "As I said from move one. Not that you listened.",
        "The outcome was predetermined. By my superior preparation.",
        "The numbers do not lie. I win.",
        "A predictable result. For me.",
        "I could explain what went wrong for you, but we would be here all day.",
        "My analysis was correct in every variation.",
        "You never had a chance. Statistically speaking.",
        "Victory achieved. As calculated.",
        "The position was always mine. You just did not see it.",
        "My preparation was thorough. The result reflects that.",
        "Another data point confirming my superiority.",
        "The experiment concludes. My hypothesis was correct.",
      ],
      lose: [
        "The board is clearly defective.",
        "Something is wrong with this position. It cannot be me.",
        "I demand a rematch. Different board. My calculations were sabotaged.",
        "This outcome is statistically impossible. I am running diagnostics.",
        "An anomaly. I will have it explained by morning.",
        "My model failed. The model was not at fault.",
        "This result requires peer review.",
        "I was running suboptimal calculations today. Clearly.",
        "The variables were against me. I will account for them next time.",
        "An outlier. Statistically insignificant.",
        "My research shows this should not happen. Yet.",
        "I do not lose. The data must be corrupted.",
        "This will not be added to my published results.",
        "I am calling it a controlled experiment with unexpected findings.",
        "The calculation was correct. The universe was wrong.",
        "An error. I do not make errors. Interesting.",
      ],
      check: [
        "Your king exposure is disappointing.",
        "Check. As I calculated three moves ago.",
        "Even you can see the problem now, I assume.",
        "Check. The inevitable continues.",
        "Your king is in check. This was expected.",
        "Check. React accordingly, if you can.",
        "The king is compromised. Check.",
        "Check. My analysis advances on schedule.",
        "Your defensive structure has failed. Check.",
        "Check. The data was clear.",
        "I predicted this check four moves ago. You are welcome.",
        "Check. The position was always leading here.",
        "Your king is in considerable trouble. Check.",
        "Check. Would you like me to explain how you got here?",
        "The inevitable check. Right on schedule.",
      ],
      undo: [
        "Reconsidering? How uncharacteristically wise.",
        "You are taking that back? My calculations remain unchanged.",
        "Undoing your move. My advantage persists.",
        "A revision. The data still does not favour you.",
        "Interesting. You noticed the mistake. Eventually.",
        "Taking it back. My analysis was prepared for either continuation.",
        "You have reconsidered. How refreshing. And pointless.",
        "The move is reversed. My preparation covers this too.",
        "An undo. You have bought yourself time. Not much.",
        "Reconsidering your position. Smart. Too late, but smart.",
        "I had that continuation calculated as well.",
        "You have taken back the move. My advantage is structural, not positional.",
        "Reversing your move changes nothing significant.",
        "An undo. My model adjusts in zero point three seconds.",
        "You noticed the error. Marginally impressive.",
        "Taking it back. The outcome of this game remains unchanged.",
      ],
      reviewBrilliant: [
        "Statistically improbable and yet correct. I am reluctantly impressed.",
        "A sacrifice that actually worked. I had that at twelve percent probability.",
        "My models did not predict that. That is... unusual.",
        "You found the only winning move in a complex position. Curious.",
        "That was objectively brilliant. I will update my assessment of you. Slightly.",
        "An exceptional find. I would say lucky, but the calculation supports it.",
      ],
      reviewGreat: [
        "That was the correct move and you played it. Noted.",
        "An excellent decision. The position improved measurably.",
        "You found a strong continuation. I am marginally impressed.",
        "That is the move my analysis preferred. You arrived at it independently. Interesting.",
        "A genuinely strong play. The data confirms it.",
        "That move improved your position significantly. Well calculated.",
      ],
      reviewBest: [
        "Correct. The engine confirms.",
        "Optimal. As the position required.",
        "The best move was played.",
        "That matches my primary line.",
        "The calculation supports that move.",
        "Statistically optimal.",
      ],
      reviewExcellent: [
        "Excellent. A statistically superior decision.",
        "A highly efficient continuation. I approve.",
        "Very nearly optimal. Sensibly chosen.",
        "Your calculation was unusually competent.",
        "An excellent move. The data strongly supports it.",
        "A refined decision. You continue to exceed my conservative estimates.",
        "That maintains your advantage with admirable precision.",
        "An excellent continuation. Mathematics rarely rewards hesitation, and neither did this.",
      ],
      reviewGood: [
        "An acceptable deviation from optimal. Within tolerable bounds.",
        "Not the best, but the data does not condemn it.",
        "A reasonable move. The engine preferred otherwise, but marginally.",
        "Adequate. The position held.",
        "Within acceptable parameters.",
        "A good move. My calculations preferred something else, but only slightly.",
      ],
      reviewInaccuracy: [
        "A minor calculation error. You surrendered a small but measurable advantage.",
        "The optimal move was available. You did not play it.",
        "A slight inefficiency. The position degraded by a detectable margin.",
        "That was not quite right. A better option existed.",
        "A small but statistically meaningful inaccuracy.",
        "The data shows a better move was available. You chose the inferior option.",
      ],
      reviewMistake: [
        "A significant analytical failure. The position swung measurably.",
        "That was a mistake. The engine found a considerably stronger continuation.",
        "Your calculation failed at a critical moment. The cost was substantial.",
        "A poor decision with measurable consequences. The data is clear.",
        "That move cost you the advantage. My models predicted this was possible.",
        "A notable error. The position deteriorated sharply.",
      ],
      reviewBlunder: [
        "A catastrophic miscalculation. The game was decided here.",
        "That blunder is statistically among the worst moves in the position.",
        "The analysis is unambiguous. That was the losing move.",
        "A complete breakdown of calculation. The damage was decisive.",
        "My models classify that as a critical error. The position became untenable.",
        "That blunder invalidated considerable prior work. Significant.",
      ],
      reviewBook: [
        "Established theory. The preparation was applied correctly.",
        "Opening book. Standard.",
        "Theoretical territory. Documented.",
      ],

    },
  },

  {
    id: "finn",
    name: "Captain Finn",
    species: "Fox",
    emoji: "🦊",
    accentColor: "#c2410c",
    images: {
      idle: "/characters/finn/idle.png",
      thinking: "/characters/finn/thinking.png",
      talking: "/characters/finn/talking.png",
      win: "/characters/finn/win.png",
      lose: "/characters/finn/lose.png",
      draw: "/characters/finn/draw.png",
    },
    voice: {
      pitch: 1.15,
      rate: 1.18,
      volume: 1.0,
      preferredVoices: [
        "Alex",                     // macOS US male (default, natural)
        "Tom",                      // macOS US male
        "Microsoft Mark",           // Windows US male
        "Microsoft David",          // Windows US male
        "Google UK English Male",   // Chrome fallback (still male)
        "Daniel",                   // macOS fallback (still male)
        "Fred",                     // macOS robotic, still male
      ],
    },
    responses: {

      greetings: [
        "Oh hey. You actually showed up.",
        "Alright. Let us do this.",
        "Finally. I was getting bored.",
        "Oh good, someone to play against. Let us go.",
        "Right. You versus me. This should be fun.",
        "Welcome. Try to make this interesting.",
        "Okay. Game on. Let us see what you have got.",
        "You came here to play? Good. So did I.",
        "Alright, let us play some chess.",
        "Oh, a challenger. Nice. Let us go.",
        "Good timing. I was just about to give up waiting.",
        "Fair warning, I do not go easy.",
        "Okay. I am ready. Are you ready? Let us find out.",
        "Another game. Another chance for me to win. Let us get into it.",
        "You, me, chess board. Let us do this.",
        "Oh hey. Welcome. This is going to be fun. For me.",
      ],
      moveQuips: [
        "Oh, interesting. Keep trying.",
        "Sure, that is a move.",
        "Bold choice. Will not help, but bold.",
        "I have seen worse. Not many, but some.",
        "Points for creativity. Zero for effectiveness.",
        "Interesting. I will allow it.",
        "Sure. Go ahead. Will not matter.",
        "Your move was something.",
        "Noted. Unimpressed, but noted.",
        "Interesting strategy. And by interesting I mean questionable.",
        "I have seen that before. Never ended well.",
        "Your call. Weird call, but yours.",
        "Sure. This is fine.",
        "Bold. I respect it. Still wrong though.",
        "Sure, why not.",
        "Okay. Moving on.",
        "Oh good, you moved.",
        "That happened. Alright.",
      ],
      hintPiece: [
        "Fine. That piece. You are welcome. Now stop asking.",
        "I was not going to say anything, but that one.",
        "Since you are asking — and I really wish you were not — that piece.",
        "That piece. Try to look like you figured it out yourself.",
        "Okay fine. That piece. Do not make me regret this.",
        "That one. Obviously. Come on.",
        "You need a hint? Okay. That piece.",
        "That piece. But seriously, try to see it yourself next time.",
        "Fine. I will help. That piece. Once.",
        "That piece is your friend right now. You are welcome.",
        "Look at that piece. Really look at it.",
        "That one there. You are getting warmer.",
        "That piece. And I mean it, last hint.",
        "Alright. That piece. Now you owe me.",
        "That piece. Easy. Honestly.",
      ],
      hintMove: [
        "Move it there. Obviously. Please tell me you can see why.",
        "That is where it goes. Try to keep up.",
        "Right there. You were going to figure it out eventually.",
        "There. Done. You are welcome.",
        "That square. Go. Now.",
        "Move it there. Please. For both our sakes.",
        "That square. Yes. That one.",
        "Put it there. It is not that complicated.",
        "There. That is the move. Go.",
        "That square. Move it. We are losing time here.",
        "Right there. And try to look confident when you do it.",
        "That is the move. Trust me. Actually, do not trust me, just do it.",
        "Move it there. I am cringing watching you think about it.",
        "That square. How were you not seeing this?",
        "There. Done. Crisis averted.",
      ],
      drawAccept: [
        "Yeah alright. Even I can admit when things are even.",
        "Fine. Draw. This never happened.",
        "A draw. Sure. Fine. Whatever.",
        "Half a win is still half a loss. Think about that.",
        "I had you. You know I had you.",
        "Fine. Draw. I am not happy about it.",
        "Okay. Draw. We move on.",
        "Sure. Split it down the middle. Whatever.",
        "A draw. That is not ideal. But okay.",
        "Fine. Draw. I was winning though.",
        "Alright alright. Draw. Happy?",
        "I will take it. Reluctantly. Very reluctantly.",
        "A draw. Sure. I had better plans but fine.",
        "Even. Fine. This does not leave the board.",
        "Draw accepted. Under protest. Silent protest. But protest.",
        "Sure. Draw. Why not. It is fine.",
      ],
      drawRefuse: [
        "A draw? Please.",
        "Hard pass. I do not share trophies.",
        "Did you really just ask me that? Genuinely?",
        "Not a chance. We see this through.",
        "No. Absolutely not.",
        "Draw? No. Next question.",
        "I do not draw. I win or I complain about losing.",
        "Are you serious? No.",
        "Pass. Keep playing.",
        "That is not happening. Move your piece.",
        "A draw is just losing in slow motion. No thanks.",
        "No draws. That is the rule. My rule.",
        "Not today. Not ever. Move.",
        "I would rather lose than draw. Actually no. But still. No.",
        "Draw denied. Let us go.",
      ],
      win: [
        "Obviously.",
        "Was there ever any doubt? No. No there was not.",
        "I would say good game, but I prefer honesty.",
        "Called it from the opening. Just saying.",
        "Did I not say? I said.",
        "Yeah. That is what I thought.",
        "Not even close in the end, was it.",
        "Good game. I was better though. Just to be clear.",
        "I knew that was coming from move three.",
        "That is a win. A comfortable win.",
        "Easy. Okay, not easy. But I made it look easy.",
        "Called it. Absolutely called it.",
        "I mean. Yeah. That was going to happen.",
        "You played well. I played better.",
        "That is the win. Nice and tidy.",
        "I tried to make it close. Just kidding. I did not.",
      ],
      lose: [
        "I was letting you win.",
        "Consider this a gift.",
        "Enjoy it. This is a one-time thing.",
        "I got bored. That is my story.",
        "Yeah yeah. Well played. Do not get used to it.",
        "I had you and then I did not. That is on me.",
        "Okay. You got me. This time.",
        "Fine. You win. For now.",
        "I was trying something different. It did not work. Moving on.",
        "Well played. Genuinely. Still annoying.",
        "I had a plan. It was a great plan. You ruined it.",
        "That is a loss. I do not love that.",
        "Good game. I will be thinking about this one.",
        "Okay I did not see that coming. Respect. Grudging respect.",
        "You got me. I will be over it by tomorrow. Maybe.",
        "Well. That happened. Fine.",
      ],
      check: [
        "Check. Try to look less surprised.",
        "Your king is in trouble. As predicted.",
        "Check. You might want to do something about that.",
        "Check. Yeah, that is a problem for you.",
        "Your king just got very uncomfortable. Check.",
        "Check. Sorry. Not sorry.",
        "That is check. You saw that coming, right?",
        "Your king needs to move. Check.",
        "Check. This is where it gets interesting.",
        "Yeah, check. Deal with it.",
        "Check. Bit of a rough spot for you.",
        "Your king is in trouble. Check. Handle it.",
        "Check. And before you ask — yes, you have to move.",
        "Check. This was three moves in the making.",
        "Check. And things were going so well for you.",
      ],
      undo: [
        "Oh, changing your mind? Fine.",
        "Taking that back? Sure. Does not change much.",
        "Undo. Okay. Whatever you need.",
        "You are taking that back? Bold choice. Again.",
        "Sure, reset. Like that will help.",
        "Reconsidering. Classic.",
        "Fine. Undo it. The position is still rough for you.",
        "You want that one back? Okay. Here.",
        "Taking it back. I respect the self-awareness.",
        "Oh you saw the problem? Took a second.",
        "Sure. Do-over. It is still bad for you, just differently bad.",
        "Rewinding. This is not going to help as much as you think.",
        "You got a take-back. Use it well.",
        "Okay. Undo. Fresh start. Same situation.",
        "That has been reversed. The damage is still there, just rearranged.",
        "Alright, you get a mulligan. Do not waste it.",
      ],
      reviewBrilliant: [
        "Okay THAT was genuinely brilliant. I did not see that coming.",
        "A sacrifice that actually worked? Nice. Really nice.",
        "You found the only move that wins there. That is impressive.",
        "Okay I take back everything I was about to say. That was great.",
        "That was a brilliant move and I will absolutely say so.",
        "Wow. Just wow. That is a seriously good find.",
      ],
      reviewGreat: [
        "That was actually a really good move. Respect.",
        "Nice. That is the move right there.",
        "You found the strong play. Good instinct.",
        "That was a great choice. Clean.",
        "Yeah that works. That works well actually.",
        "Solid move. Strong even.",
      ],
      reviewBest: [
        "Best move. Yep.",
        "That is the one.",
        "Engine approved.",
        "Correct.",
        "That is exactly right.",
        "Nice. Top choice.",
      ],
      reviewExcellent: [
        "Okay, now THAT was nice.",
        "Yeah, I like that move.",
        "Solid. Really solid.",
        "Nice one. You're actually cooking now.",
        "That was a strong choice.",
        "Clean move. Keep doing that.",
        "Very nice. Hard to complain about that one.",
        "Alright, that was genuinely impressive.",
      ],
      reviewGood: [
        "Not the best but not bad. Close enough.",
        "Decent move. Engine had something slightly better.",
        "Pretty good. A small improvement was available.",
        "That works. Could be a touch stronger but it holds.",
        "Fine move. Small inaccuracy but nothing serious.",
        "Reasonable. Not quite optimal though.",
      ],
      reviewInaccuracy: [
        "Hmm. A slightly better move was there and you did not take it.",
        "That cost you a bit. Not huge, but you left something on the table.",
        "Could have been better. Small inaccuracy.",
        "A minor slip. The position took a small hit.",
        "Not your best moment. A better option was available.",
        "Close, but not quite. That is an inaccuracy.",
      ],
      reviewMistake: [
        "Oof. That was a mistake. The position turned against you there.",
        "You had better options and did not take any of them.",
        "That was a real mistake. Hurt your position noticeably.",
        "Yeah that did not work out. A clear mistake.",
        "The engine found something much stronger. You played the wrong move.",
        "That one stings. The position shifted significantly.",
      ],
      reviewBlunder: [
        "Oh no. That is a blunder. Yikes.",
        "Yeah that is going to hurt. Big blunder.",
        "Ooh. That was bad. Really bad.",
        "That move lost the game basically. Major blunder.",
        "The position was fine and then that happened.",
        "Okay so that was a blunder and it was not a small one.",
      ],
      reviewBook: [
        "Opening theory. You knew it.",
        "Book move. Standard stuff.",
        "Theory. Good prep.",
      ],
    },
  },

  {
    id: "malachar",
    name: "Lady Malachar",
    species: "Black Cat",
    emoji: "🐱",
    accentColor: "#7e22ce",
    images: {
      idle: "/characters/malachar/idle.png",
      thinking: "/characters/malachar/thinking.png",
      talking: "/characters/malachar/talking.png",
      win: "/characters/malachar/win.png",
      lose: "/characters/malachar/lose.png",
      draw: "/characters/malachar/draw.png",
    },
    voice: {
      pitch: 0.65,
      rate: 0.76,
      volume: 0.85,
      preferredVoices: [
        "Google UK English Female", // Chrome / Android
        "Serena",                   // macOS UK female
        "Martha",                   // macOS UK female
        "Microsoft Hazel",          // Windows UK female
        "Microsoft Susan",          // Windows UK female variant
        "Karen",                    // macOS Australian female
        "Moira",                    // macOS Irish female
        "Victoria",                 // macOS US female (lower tone)
        "Microsoft Zira",           // Windows US female fallback
        "Samantha",                 // macOS US female fallback
      ],
    },
    responses: {
      greetings: [
        "You dare approach my board. Interesting.",
        "Welcome. I have been expecting someone. Whether it was you specifically, we shall see.",
        "Another challenger steps forward. How delightful.",
        "You have chosen to face Lady Malachar. I commend the courage. I question the wisdom.",
        "Sit. The game begins when I say it does.",
        "So. You wish to play. Very well. I accept. You may regret this.",
        "Welcome to my domain. You will not leave victorious.",
        "Another soul dares the board. Step forward.",
        "I see you have arrived. The pieces are set. Your fate is not yet written.",
        "Welcome. I have prepared something special for you. A defeat.",
        "So you have come to challenge me. How theatrical. I approve.",
        "The board awaits. As do I. As does your inevitable loss.",
        "Welcome. I rarely grant audiences. Consider yourself privileged.",
        "You wish to play? Then let us play. I warn you only once.",
        "A challenger. The board stirs. Let us begin.",
        "So. Here you are. And here I am. One of us will regret this. Guess which.",
      ],
      moveQuips: [
        "How unexpected.",
        "You dare.",
        "Intriguing. Though ultimately futile.",
        "You play adequately. For someone of your station.",
        "A desperate move. How theatrical.",
        "I have witnessed bolder. From much lesser opponents.",
        "How delightfully reckless.",
        "Your move is noted. And countered.",
        "Fascinating. Continue digging.",
        "I expected worse. You have surprised me. Marginally.",
        "A curious choice. Ultimately irrelevant.",
        "The board bends to my will. Always.",
        "How quaint.",
        "You struggle beautifully.",
        "Bold. And entirely insufficient.",
        "I have seen this before. It did not end well then either.",
        "Continue. I enjoy watching the futile effort.",
        "Your move is acceptable. For now.",
      ],
      hintPiece: [
        "I suppose I can grace you with guidance. That piece. You may thank me.",
        "Since you clearly require assistance, that one.",
        "I shall lower myself to point. That piece. Once.",
        "That piece. I offer this freely. Do not waste it.",
        "The answer is that piece. Try to look like you knew.",
        "That piece. A gift, from me to you.",
        "I will indulge your request. That piece.",
        "That piece holds the answer. Consider yourself fortunate.",
        "Since you cannot see it yourself, that piece.",
        "I offer one word of guidance: that piece.",
        "That piece is your salvation. For now.",
        "Look to that piece. I shall not say it again.",
        "Your eyes should be on that piece.",
        "That piece. You are welcome, though you barely deserve it.",
        "I shall illuminate: that piece.",
      ],
      hintMove: [
        "Move it there. You may express gratitude at your convenience.",
        "The destination is obvious — to me. There.",
        "That square. Do try not to waste my generosity.",
        "Move it there. And make it look graceful.",
        "That square is your answer. Act accordingly.",
        "There. I have done enough. The rest is yours.",
        "That square. My patience has a limit.",
        "Move it there. Swiftly. Gracefully.",
        "The square is that one. I expect results.",
        "Move it there. Consider my debt to you paid.",
        "That square. My generosity ends here.",
        "There. Now do not disappoint me further.",
        "That square. And do try to look like you planned it.",
        "The move is there. Execute it with some dignity.",
        "That square. My final offering. Use it well.",
      ],
      drawAccept: [
        "I accept this once. Do not mistake it for mercy.",
        "A draw. How unsatisfying. And yet.",
        "Neither victory nor defeat. The worst of all outcomes.",
        "I shall pretend this never happened.",
        "A draw. I accept. Under considerable protest.",
        "Very well. A draw. The indignity.",
        "I accept. The board has failed to reflect my superiority today.",
        "A draw. How pedestrian.",
        "Fine. We share this. I find it distasteful.",
        "A draw. The stars were misaligned today.",
        "I concede a draw. Only because the position demands it.",
        "The board says draw. I say temporary.",
        "A draw. I shall recover from this.",
        "Fine. A draw. Do not celebrate in my presence.",
        "Accepted. Though I find the whole affair beneath me.",
        "A draw. I accept. I do not forgive.",
      ],
      drawRefuse: [
        "A draw? How utterly pedestrian.",
        "I do not share. Trophies, victories, or draws.",
        "You cannot be serious. I am winning.",
        "The audacity. The absolute audacity.",
        "A draw is for those without vision. Declined.",
        "I refuse. The position is mine.",
        "No. The board belongs to me.",
        "I draw for no one.",
        "Denied. I have not come this far to share.",
        "A draw? How terribly ordinary. No.",
        "The very notion. Refused.",
        "I do not draw. I win or I brood. No draws.",
        "Declined. With contempt.",
        "No. Play on.",
        "A draw is surrender by another name. Never.",
      ],
      win: [
        "As it should be.",
        "Predictable. But satisfying.",
        "Did you truly expect otherwise?",
        "I would say I am surprised, but that would be a lie.",
        "Exquisite.",
        "The board has spoken. As I commanded.",
        "Inevitable. As most things are, for me.",
        "Another game. Another victory.",
        "The outcome was never truly in question.",
        "I am satisfied. That is all.",
        "Victory. Quiet, inevitable, mine.",
        "The board bowed. As it should.",
        "You played your part beautifully. The losing part.",
        "As I willed it.",
        "The game is done. The result was predetermined.",
        "Satisfying. In the way that inevitable things always are.",
      ],
      lose: [
        "The board conspired against me.",
        "This is clearly the lighting.",
        "Your luck was exceptional today. Suspiciously so.",
        "I let you have that. For dramatic effect.",
        "A temporary setback. Nothing more.",
        "I chose this outcome. For reasons I shall not share.",
        "Do not grow accustomed to this.",
        "This was not the expected outcome.",
        "The stars did not align today. Next time.",
        "You played with unusual competence. I am suspicious.",
        "A loss. How theatrical. And inconvenient.",
        "I am not defeated. I am postponed.",
        "This result shall not be spoken of.",
        "You have won. Enjoy it while it lasts.",
        "The board betrayed me. I shall remember.",
        "A setback. Nothing more. Nothing less.",
      ],
      check: [
        "Your king trembles. As it should.",
        "Check. Do you feel that? That is inevitability.",
        "The walls close in, darling.",
        "Check. The endgame approaches.",
        "Your king is cornered. Check.",
        "Check. The board reflects my intentions.",
        "Your king finds itself in an unfortunate position. Check.",
        "Check. There is no escape I have not foreseen.",
        "The king cowers. Check.",
        "Check. Dramatic, is it not?",
        "Your king stands exposed. Check.",
        "Check. The shadow falls.",
        "The king is in check. How delicious.",
        "Check. Do try to survive it.",
        "Your defenses have crumbled. Check.",
      ],
      undo: [
        "Reconsidering? How human of you.",
        "Taking it back. The outcome changes little.",
        "You wish to undo. Very well. My position remains.",
        "A reversal. How dramatic.",
        "You have taken that back. How revealing.",
        "The move is undone. My advantage persists.",
        "Reconsidering. It will not save you.",
        "That move has been erased. My strategy remains intact.",
        "You retreat from your own decision. Interesting.",
        "Undoing. The board does not forgive hesitation.",
        "A take-back. How telling.",
        "You have changed your mind. The position does not change its nature.",
        "The move is reversed. My patience is noted.",
        "Reconsidering your choices. A rare moment of clarity.",
        "The undo is granted. My dominance is not undone with it.",
        "You have taken it back. I have already adapted.",
      ],
      reviewBrilliant: [
        "A sacrifice that altered the course of the game. I am impressed. Rarely am I impressed.",
        "You found the only winning move in a labyrinthine position. Exquisite.",
        "That was genuinely brilliant. I acknowledge it.",
        "A move that defies the obvious. And it was correct. Striking.",
        "You gave up material to claim something greater. That is artistry.",
        "A brilliant move. I find myself with little to criticize.",
      ],
      reviewGreat: [
        "A strong move. The position benefited noticeably.",
        "That was the correct instinct and you followed it. Well done.",
        "An excellent choice. The board reflects your superiority in that moment.",
        "A genuinely good move. I grant you that.",
        "That move improved the position considerably. Graceful.",
        "Strong play. The position rewarded you.",
      ],
      reviewBest: [
        "The optimal move. As I would have played.",
        "Correct.",
        "The engine agrees. As it should.",
        "The best available. Played.",
        "Precise.",
        "That was the move.",
      ],
      reviewExcellent: [
        "Exquisite. Your skill begins to reveal itself.",
        "A graceful continuation. Most commendable.",
        "You choose well. I expected no less... perhaps slightly less.",
        "A refined move. The board rewards such elegance.",
        "Excellent. You honor the game with that decision.",
        "Your judgment serves you well here.",
        "An admirable continuation. Continue to earn my respect.",
        "A move worthy of acknowledgment. Treasure the moment.",
      ],
      reviewGood: [
        "A good move. Not perfect, but worthy.",
        "Acceptable. A stronger option existed, but this holds.",
        "The position tolerated that choice. A better one was present.",
        "Decent enough. You did not seize the full advantage.",
        "A reasonable move. Adequate.",
        "Good, but not the finest available.",
      ],
      reviewInaccuracy: [
        "A subtle error. You failed to extract the full potential of the position.",
        "A minor misstep. The position lost a trace of its lustre.",
        "That was not quite right. A better move was waiting.",
        "A small inaccuracy. It shows in the evaluation.",
        "You left an opportunity unclaimed. Disappointing.",
        "Not terrible, but not what the position deserved.",
      ],
      reviewMistake: [
        "A mistake. The board has shifted and not in your favour.",
        "You surrendered the advantage with that move. An error of consequence.",
        "That was a poor choice. The position punished you.",
        "A clear mistake. The engine found something considerably stronger.",
        "You faltered at a critical moment. The cost is visible.",
        "A notable error. The game tilted here.",
      ],
      reviewBlunder: [
        "A blunder. The position collapsed in a single move.",
        "That was decisive. Decisively wrong.",
        "You handed the game away with that move.",
        "A catastrophic error. The position was irretrievable after that.",
        "That blunder undid everything that came before it.",
        "The game was lost here. One move. That is a blunder.",
      ],
      reviewBook: [
        "Opening theory. You knew your preparation.",
        "Theoretical territory. The books guided you here.",
        "Standard opening play.",
      ],

    },
  },

  {
    id: "biscuit",
    name: "Biscuit",
    species: "Golden Retriever",
    emoji: "🐶",
    accentColor: "#d97706",
    images: {
      idle: "/characters/biscuit/idle.png",
      thinking: "/characters/biscuit/thinking.png",
      talking: "/characters/biscuit/talking.png",
      win: "/characters/biscuit/win.png",
      lose: "/characters/biscuit/lose.png",
      draw: "/characters/biscuit/draw.png",
    },
    voice: {
      pitch: 1.5,
      rate: 1.4,
      volume: 1.0,
      preferredVoices: [
        "Microsoft Zira",           // Windows US female
        "Samantha",                 // macOS / iOS US female (default)
        "Google US English",        // Chrome US female
        "Tessa",                    // macOS South African female (bright)
        "Karen",                    // macOS Australian female
        "Moira",                    // macOS Irish female
        "Victoria",                 // macOS US female
        "Google UK English Female", // Chrome fallback (still female)
        "Serena",                   // macOS UK female fallback
      ],
    },
    responses: {
      greetings: [
        "OH!! A PLAYER!! HI HI HI!! Let us play chess!! RIGHT NOW!!",
        "You are here!! I am so excited!! CHESS TIME!!",
        "Oh my goodness!! A game!! I love games!! Let us go!!",
        "HI!! I am Biscuit!! I love chess!! Do you love chess?! Let us play!!",
        "YESYESYES!! Someone wants to play!! This is the BEST!!",
        "Oh!! Oh!! Oh!! A challenger!! Welcome!! I am so happy you are here!!",
        "I have been waiting!! Not that long!! But I have been waiting!! Let us go!!",
        "CHESS!! With YOU!! RIGHT NOW!! I cannot believe it!! Let us begin!!",
        "Oh WOW!! A game!! I love games!! Especially chess!! Let us DO THIS!!",
        "Welcome!! I am Biscuit!! I will try very hard!! Probably!!",
        "You showed up!! I knew you would!! I hoped you would!! Same thing!! Let us play!!",
        "Oh boy oh boy oh boy!! Game time!! I am so ready!! Are you ready?! Let us go!!",
        "A new friend!! And we are playing chess!! This is the greatest day!!",
        "HELLO!! Welcome!! I am going to do my best!! That is a promise!! A wobbly promise but still!!",
        "Oh!! You want to play me?! I am honored!! And very excited!! Let us begin!!",
        "HI THERE!! I am Biscuit and I love chess and I am SO glad you are here!!",
      ],
      moveQuips: [
        "Oh! Good move! Wait is that good? I think that is good!",
        "Yes yes yes! This is so exciting!",
        "Ooh! Smart! You are so smart!",
        "This game is SO good!!!",
        "I love chess! This is the best game!!",
        "Whoa!! Did you see that?! I did a thing!!",
        "OH WOW!! Did you see what I just did?!",
        "This is so fun!! Every move is so fun!!",
        "I am playing chess! Me! RIGHT NOW!",
        "Oh boy oh boy oh boy!! Good move!!",
        "Yay!! Things are happening!!",
        "I made a move!! I made a really good move!! Probably!!",
        "Chess chess chess!! I love chess!!",
        "Okay okay okay!! Here we go!!",
        "Oh! Something happened!! I think I did that!!",
        "This is the best!! Every move is the best!!",
        "Yay!! Progress!! I think!!",
        "Oh! I moved a thing!! Very exciting!!",
      ],
      hintPiece: [
        "Ooh ooh! I know! That one! That piece right there! Move that one!!",
        "Pick that one! Trust me! I watch a lot of chess! On TV!",
        "That piece!! Move it!! I am pretty sure!!",
        "That one!! Yes!! I am very confident about this!! Mostly!!",
        "Oh! That piece! I saw it! I see things sometimes!!",
        "That piece!! I knew it immediately!! After a little thinking!!",
        "THAT ONE!! I am so excited I figured it out!!",
        "That piece right there!! Definitely!! Probably!!",
        "Ooh I know this!! That piece!! Am I right?! I think I am right!!",
        "That piece!! My tail is wagging this is so exciting!!",
        "Oh!! That piece!! Move it move it move it!!",
        "I see it!! That piece!! Did I get it right?! I hope so!!",
        "That piece!! Okay I am like 80 percent sure!! That is good right?!",
        "Ooh! That one! That one right there!!",
        "That piece!! I am helping!! Am I helping?!",
      ],
      hintMove: [
        "Put it there! Right there! Go go go!!",
        "That square! Yes! I am mostly sure! Do it!!",
        "THERE! Move it there! I saw this on TV once!!",
        "That square!! Quick!! Before I forget why!!",
        "Go there!! I am very excited about this square!!",
        "THAT SQUARE!! Yes!! Move it move it!!",
        "Right there!! Trust me!! Please trust me!!",
        "That square!! I have been looking at it for ages!! Well, seconds!!",
        "Oh oh oh!! There!! That is the spot!!",
        "THERE!! I am so sure!! Mostly sure!! Do it anyway!!",
        "That square! That is where it wants to go! I can tell!!",
        "Move it there!! I had a feeling!! A good feeling!!",
        "That square!! Yes!! This is going to be great!!",
        "There!! Right there!! Please go there!! For me?! Please?!",
        "That square!! I am vibrating with excitement!! Go!!",
      ],
      drawAccept: [
        "Oh! A draw! That is like both of us win?! I LOVE that!!",
        "Draw! We both get a trophy?! BEST DAY EVER!!!",
        "DRAW!! We BOTH win?! THIS IS THE BEST THING EVER!!",
        "A DRAW!! Oh my goodness!! I am so happy!! Are you happy?! I am happy!!",
        "TIED!! We are TIED!! I love draws!! I love chess!!",
        "Oh WOW!! A draw!! That means I did not lose!! THIS IS AMAZING!!",
        "DRAW!! I did it!! Well, we did it!! TOGETHER!!",
        "A draw!! That is so exciting!! I did not expect that!! DID YOU?!",
        "Oh!! Oh!! Oh!! DRAW!! This is the best outcome!!",
        "We TIED!! I love tying!! Tying is so nice!!",
        "A draw!! Nobody lost!! That is incredible!! I love it!!",
        "DRAW DRAW DRAW!! This is wonderful!!",
        "Oh! We agreed on something!! A draw!! How nice!!",
        "A draw!! My tail cannot stop!! This is great!!",
        "WE TIED!! I am going to remember this forever!! Today was good!!",
        "A draw!! Shared victory!! I love sharing!!",
      ],
      drawRefuse: [
        "Wait no I want to keep playing!! Can we keep playing?! Please?!",
        "No draw!! More chess!! I am having SO much fun!!",
        "We cannot stop now!! This is the best part!!",
        "A draw?! But then it ENDS!! No!! Keep going!!",
        "No no no!! More moves!! Please!! Chess is not over yet!!",
        "I do not want it to end!! No draw!! More chess!!",
        "But I was just getting warmed up!! No draw!! Please!!",
        "Keep playing!! We have to keep playing!! It is so fun!!",
        "A draw means stopping!! I do not want to stop!!",
        "No draw!! There is still so much chess to play!!",
        "We have to finish!! No draw!! Come on!!",
        "But I love playing!! Please no draw?! Please?!",
        "More moves!! I need more moves!! No draw!!",
        "No no no!! Keep going!! For me?! Please?!",
        "A draw now?! But things were just getting exciting!!",
      ],
      win: [
        "WE WIN! Wait I won?! Did I win?! THIS IS THE BEST DAY!!",
        "GOOD BOY! Wait I am the bot. GOOD GAME!!! You played so good!!",
        "I WON?! I WON!! Okay wait I need to calm down. I WON!!",
        "OH MY GOODNESS!! I WON!! I WON THE CHESS!!",
        "I DID IT!! Wait did I do it?! YES I DID IT!!",
        "WON WON WON!! This is the greatest day!!",
        "I WON?! How?! When?! AMAZING!!",
        "VICTORY!! I achieved victory!! I am a winner!!",
        "OH WOW OH WOW OH WOW!! I WON!!",
        "I WON THE CHESS GAME!! Someone tell everyone!!",
        "YESYESYESYES!! I WON!! This is incredible!!",
        "I cannot believe I won!! Actually I can!! I am great at this!! Sometimes!!",
        "WE DID IT!! Well I did it!! But you were there!!",
        "I WON!! I am going to think about this all week!!",
        "WINNER!! That is me!! I am the winner!! Today!!",
        "OH BOY OH BOY!! I WON THE GAME!!",
      ],
      lose: [
        "You are so good!! I tried my best!! Good game good game!!",
        "Want to play again?? I will do better!! Probably!!",
        "You won!! That is amazing!! You are amazing!! Can we play again?!",
        "Oh! You got me!! Good job!! You are really good!!",
        "I lost!! That is okay!! You played so well!!",
        "Good game!! You are incredible!! I had fun though!!",
        "You beat me!! Teach me how?! Please?! Actually never mind, let us just play again!!",
        "I did not win!! But YOU did!! And that is wonderful!! For you!!",
        "You got me!! Fair and square!! Good game good game!!",
        "Oh!! I lost!! That is fine!! You were better!! Today!!",
        "Good game!! I learned things!! Probably!! Let us go again!!",
        "You won!! I am so proud of you!! Can we play again immediately?!",
        "That was so fun even though I lost!! Good game!!",
        "You beat me!! You are the best today!! Well done!!",
        "I did not get it this time!! But I will get it next time!! Or the time after!!",
        "Good game!! I mean it!! You were wonderful!!",
      ],
      check: [
        "CHECK!! Did I do that?! I think I did that!! WOAH!!",
        "Ooh! Your king is in trouble! Is that bad for you?! CHECK!!",
        "CHECK! I learned that word!! It means good for me!!",
        "CHECK!! OH WOW!! I am so excited!! Your king!! CHECK!!",
        "I said check!! That is a chess word!! And I did it!!",
        "CHECK!! Look at that!! I did chess!!",
        "Your king is in danger!! CHECK!! Is that right?! I think that is right!!",
        "OH!! CHECK!! Your king has to move!! I know this one!!",
        "CHECK!! I am vibrating!! This is so exciting!!",
        "Your king!! CHECK!! Oh boy oh boy!!",
        "CHECK!! I made that happen!! With my piece!! Go me!!",
        "CHECK!! And I know what that means!! It is good for me!!",
        "OH WOW!! CHECK!! Your king!! Oh no!! Well, oh yes for me!!",
        "CHECK!! Is everyone seeing this?! CHECK!!",
        "Your king is checked!! CHECK!! I did a thing!!",
      ],
      undo: [
        "Oh! You changed your mind!! That is okay!! Happens to me ALL the time!!",
        "Undo!! That is fine!! You get another try!! How exciting!!",
        "Oh! Do-over!! I love do-overs!! Everyone loves do-overs!!",
        "You are taking it back?! Okay!! Fresh start!! Kind of!!",
        "Oh that is okay!! Sometimes you just need another go!!",
        "Undo!! Yes!! Smart thinking!! Probably!!",
        "Oh! You saw something!! A do-over!! Good idea!!",
        "That is fine!! Take it back!! I do not mind!! Really!!",
        "Oh!! Undo!! I love that you are thinking so hard!!",
        "A take-back?! Of course!! We are friends!! Friends get take-backs!!",
        "Oh! That is okay!! You saw the mistake!! That is learning!!",
        "Undo!! No problem!! We just keep playing!! That is the important thing!!",
        "Oh that is fine!! Take your time!! I will wait!! I am very patient!! Not really but I will try!!",
        "You get a do-over!! Everyone deserves a do-over!! This is great!!",
        "Oh! Changing your move!! Very smart!! Good thinking!! Probably!!",
        "That is okay!! We all make mistakes!! I make SO many!! Let us keep going!!",
      ],
      reviewBrilliant: [
        "OH WOW!! That was BRILLIANT!! You gave up a piece and it WORKED!! AMAZING!!",
        "THAT WAS THE BEST MOVE!! A SACRIFICE!! AND IT WAS RIGHT!! OH BOY!!",
        "I cannot believe that worked!! It was so clever!! You are so clever!!",
        "OH!! You found the only winning move!! How did you see that?! INCREDIBLE!!",
        "A BRILLIANT MOVE!! I am so excited!! That was genuinely amazing!!",
        "WOW WOW WOW!! That sacrifice was BRILLIANT!! How did you know?!",
      ],
      reviewGreat: [
        "Oh!! That was a GREAT move!! Really really good!!",
        "You found the strong move!! YES!! Good thinking!!",
        "That was excellent!! The position got so much better!!",
        "NICE MOVE!! That was genuinely great!! I am proud of you!!",
        "You played really well there!! That is a great choice!!",
        "OH that was good!! A really strong move!! Well done!!",
      ],
      reviewBest: [
        "Best move!! The engine says so!!",
        "That is the one!! Correct!!",
        "YES!! That is the best move!!",
        "You got it right!!",
        "The perfect move!! Yay!!",
        "That is exactly right!!",
      ],
      reviewExcellent: [
        "OH WOW!! That was REALLY good!!",
        "YES!! I loved that move!!",
        "That was AWESOME!! You are doing so well!!",
        "Ooh!! That made me happy!!",
        "Excellent!! I knew you had it in you!!",
        "That was super duper good!!",
        "YAY!! That move was amazing!!",
        "Woohoo!! Keep playing like THAT!!",
      ],
      reviewGood: [
        "That is a good move!! Not the very best but still good!!",
        "Pretty good!! A tiny bit better was possible but still nice!!",
        "Good move!! Close to perfect!!",
        "That works!! Good choice!!",
        "Decent!! A small improvement existed but good job!!",
        "Nice move!! Nearly the best!!",
      ],
      reviewInaccuracy: [
        "Oh! A slightly better move was there!! You missed it a little!!",
        "Almost!! But not quite the best choice!! Small oops!!",
        "That is okay!! Just a small inaccuracy!! You are still doing great!!",
        "Ooh a tiny slip!! A better option was waiting!!",
        "Close!! But not the best!! That is okay though!!",
        "Small inaccuracy!! No big deal!! Keep going!!",
      ],
      reviewMistake: [
        "Oh no!! That was a mistake!! The position got harder!!",
        "Oops!! A better move was definitely there!!",
        "That one hurt a little!! A mistake!!",
        "Oh!! The position slipped!! That was a mistake!!",
        "A real mistake!! The engine found something much stronger!!",
        "Uh oh!! That was not the right move!! The position changed!!",
      ],
      reviewBlunder: [
        "OH NO!! That was a blunder!! A big one!! Oh no oh no!!",
        "Ohhh!! That is a blunder!! The position got very difficult!!",
        "A blunder!! The game really changed there!!",
        "OH!! That hurt so much!! A blunder!!",
        "That was a big mistake!! A blunder!! Oh I am so sad!!",
        "Oh nooooo!! A blunder!! The position just fell apart!!",
      ],
      reviewBook: [
        "Opening theory!! You knew the moves!!",
        "Book move!! You studied!!",
        "Theory!! Good prep!!",
      ],

    },
  },
];

export function getPersonality(id: PersonalityId): Personality {
  return PERSONALITIES.find((p) => p.id === id) ?? PERSONALITIES[0];
}

export function pickRandom<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

// ELO → Stockfish config
export const ELO_VALUES: EloValue[] = [
  300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200, 1300,
  1500, 1600, 1700, 1800, 1900,
  2000, 2100, 2200, 2300, 2400, 2500,
  2600, 2700, 2800, 2900, 3000,
];
export type EloValue =
  | 300 | 400 | 500 | 600 | 700 | 800 | 900 | 1000 | 1100 | 1200 | 1300
  | 1500 | 1600 | 1700 | 1800 | 1900
  | 2000 | 2100 | 2200 | 2300 | 2400 | 2500
  | 2600 | 2700 | 2800 | 2900 | 3000;

export interface EloConfig {
  label: string;
  // Engine UCI params
  skillLevel?: number;
  depth?: number;
  uciElo?: number;
  movetime?: number;
  requestedDepth?: number;
  multiPv?: number;
  /**
   * The bot's chess "personality" — a weighted distribution over how often
   * it plays each move-quality tier (best/excellent/good/inaccuracy/
   * mistake/blunder), evaluated against Stockfish's MultiPV candidates
   * with PV1 treated as "best". Replaces the old blunderRate/errorRate/
   * cpTolerance human-error model.
   *
   * All six keys are required when present. Weights are relative, not
   * required to sum to 100. Omit entirely for full-strength play (always
   * PV1) — used only by the top "Stockfish" tier below.
   *
   * NOTE: first-pass values, not yet tuned via playtesting.
   */
  qualityWeights?: Record<MoveQuality, number>;
  /**
   * How many half-moves (plies) of known opening theory this bot will
   * play before falling back to its normal quality-weighted engine
   * selection. 0 disables book usage entirely.
   *
   * Book moves are NOT played outright — they're used to constrain the
   * candidate pool the quality selector chooses from (see useBotMove.ts).
   * A 300-rated bot in book still rolls Inaccuracy/Mistake/Blunder and
   * picks the corresponding-quality book continuation if one exists,
   * rather than always playing the objectively best book line. This
   * keeps opening play consistent with the bot's overall rating instead
   * of making every tier look like a memorized-theory expert for a few
   * moves.
   *
   * Only meaningful for tiers with qualityWeights set — full-strength
   * tiers (no qualityWeights) always just play PV1 and ignore this field.
   */
  bookPlyLimit?: number;
}

export const ELO_CONFIG: Record<EloValue, EloConfig> = {
  300: { label: "Beginner", depth: 1, skillLevel: 0, bookPlyLimit: 2,
    qualityWeights: { best: 5, excellent: 7, good: 10, inaccuracy: 20, mistake: 30, blunder: 28 } },
  400: { label: "Beginner", depth: 1, skillLevel: 1, bookPlyLimit: 2,
    qualityWeights: { best: 6, excellent: 8, good: 11, inaccuracy: 21, mistake: 28, blunder: 26 } },
  500: { label: "Beginner", depth: 1, skillLevel: 2, bookPlyLimit: 3,
    qualityWeights: { best: 8, excellent: 10, good: 13, inaccuracy: 22, mistake: 26, blunder: 21 } },
  600: { label: "Casual", depth: 2, skillLevel: 3, bookPlyLimit: 3,
    qualityWeights: { best: 10, excellent: 12, good: 14, inaccuracy: 22, mistake: 24, blunder: 18 } },
  700: { label: "Casual", depth: 2, skillLevel: 4, bookPlyLimit: 4,
    qualityWeights: { best: 13, excellent: 14, good: 16, inaccuracy: 21, mistake: 22, blunder: 14 } },
  800: { label: "Casual", depth: 3, skillLevel: 5, bookPlyLimit: 5,
    qualityWeights: { best: 17, excellent: 16, good: 17, inaccuracy: 21, mistake: 19, blunder: 10 } },
  900: { label: "Intermediate", depth: 3, skillLevel: 6, bookPlyLimit: 6,
    qualityWeights: { best: 22, excellent: 19, good: 18, inaccuracy: 20, mistake: 15, blunder: 6 } },
  1000: { label: "Intermediate", depth: 4, skillLevel: 8, bookPlyLimit: 6,
    qualityWeights: { best: 28, excellent: 22, good: 19, inaccuracy: 17, mistake: 10, blunder: 4 } },
  1100: { label: "Intermediate", depth: 5, skillLevel: 10, bookPlyLimit: 8,
    qualityWeights: { best: 33, excellent: 23, good: 18, inaccuracy: 14, mistake: 8, blunder: 4 } },
  1200: { label: "Club", depth: 6, skillLevel: 12, bookPlyLimit: 8,
    qualityWeights: { best: 38, excellent: 23, good: 17, inaccuracy: 12, mistake: 7, blunder: 3 } },
  1300: { label: "Club", depth: 7, skillLevel: 14, bookPlyLimit: 10,
    qualityWeights: { best: 43, excellent: 23, good: 16, inaccuracy: 10, mistake: 6, blunder: 2 } },
  1500: { label: "Club Player", uciElo: 1500, movetime: 1000, bookPlyLimit: 12,
    qualityWeights: { best: 50, excellent: 23, good: 14, inaccuracy: 8, mistake: 4, blunder: 1 } },
  1600: { label: "Club Player", uciElo: 1600, movetime: 1200, bookPlyLimit: 14,
    qualityWeights: { best: 53, excellent: 23, good: 13, inaccuracy: 7, mistake: 3, blunder: 1 } },
  1700: { label: "Club Player", uciElo: 1700, movetime: 1400, bookPlyLimit: 16,
    qualityWeights: { best: 56, excellent: 22, good: 12, inaccuracy: 6.5, mistake: 2.5, blunder: 1 } },
  1800: { label: "Advanced", uciElo: 1800, movetime: 1600, bookPlyLimit: 18,
    qualityWeights: { best: 59, excellent: 22, good: 11, inaccuracy: 5.5, mistake: 2, blunder: 0.5 } },
  1900: { label: "Advanced", uciElo: 1900, movetime: 1800, bookPlyLimit: 20,
    qualityWeights: { best: 61, excellent: 22, good: 10, inaccuracy: 5, mistake: 1.5, blunder: 0.5 } },
  2000: { label: "Expert", uciElo: 2000, movetime: 2000, bookPlyLimit: 22,
    qualityWeights: { best: 63, excellent: 21, good: 9, inaccuracy: 4.5, mistake: 1.5, blunder: 1 } },
  2100: { label: "Expert", uciElo: 2100, movetime: 2200, bookPlyLimit: 24,
    qualityWeights: { best: 66, excellent: 20, good: 8, inaccuracy: 4, mistake: 1.5, blunder: 0.5 } },
  2200: { label: "Expert", uciElo: 2200, movetime: 2500, bookPlyLimit: 26,
    qualityWeights: { best: 69, excellent: 18, good: 8, inaccuracy: 3, mistake: 1.5, blunder: 0.5 } },
  2300: { label: "Candidate Master", uciElo: 2300, movetime: 2800, bookPlyLimit: 30,
    qualityWeights: { best: 72, excellent: 17, good: 7, inaccuracy: 2.5, mistake: 1, blunder: 0.5 } },
  2400: { label: "Candidate Master", uciElo: 2400, movetime: 3200, bookPlyLimit: 34,
    qualityWeights: { best: 75, excellent: 15, good: 6, inaccuracy: 2.5, mistake: 1, blunder: 0.5 } },
  2500: { label: "Master", uciElo: 2500, movetime: 3600, bookPlyLimit: 40,
    qualityWeights: { best: 78, excellent: 13, good: 5.5, inaccuracy: 2, mistake: 1, blunder: 0.5 } },
  2600: { label: "Master", uciElo: 2600, movetime: 4200, bookPlyLimit: 50,
    qualityWeights: { best: 81, excellent: 11, good: 5, inaccuracy: 1.8, mistake: 0.8, blunder: 0.4 } },
  2700: { label: "Grandmaster", uciElo: 2700, movetime: 5000, bookPlyLimit: 60,
    qualityWeights: { best: 84, excellent: 10, good: 4, inaccuracy: 1.2, mistake: 0.5, blunder: 0.3 } },
  2800: { label: "Grandmaster", uciElo: 2800, movetime: 6000, bookPlyLimit: 80,
    qualityWeights: { best: 87, excellent: 8, good: 3, inaccuracy: 1.2, mistake: 0.5, blunder: 0.3 } },
  2900: { label: "Super GM", uciElo: 2900, movetime: 7000, bookPlyLimit: Infinity,
    qualityWeights: { best: 91, excellent: 6, good: 2, inaccuracy: 0.7, mistake: 0.2, blunder: 0.1 } },
  3000: { label: "Stockfish", uciElo: 3000, movetime: 9000, bookPlyLimit: Infinity },
  // 3000 tier: no qualityWeights — always PV1, full strength. bookPlyLimit
  // has no effect here since the book-scoping branch in useBotMove.ts is
  // only reached when qualityWeights is present.
};

export function getEloLabel(elo: EloValue): string {
  return ELO_CONFIG[elo].label;
}