/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorialRouteImport } from './routes/tutorial'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPlayRouteImport } from './routes/_app.play'
import { Route as AppImportRouteImport } from './routes/_app.import'
import { Route as AppGamesRouteImport } from './routes/_app.games'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppPlayPvpRouteImport } from './routes/_app.play.pvp'
import { Route as AppGamesStudiesRouteImport } from './routes/_app.games.studies'
import { Route as AppGamesMyGamesRouteImport } from './routes/_app.games.my-games'
import { Route as AppGamesImportedRouteImport } from './routes/_app.games.imported'
import { Route as AppAnalysisGameIdRouteImport } from './routes/_app.analysis.$gameId'
import { Route as AppGamesStudiesStudyIdRouteImport } from './routes/_app.games.studies.$studyId'

const TutorialRoute = TutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPlayRoute = AppPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesRoute = AppGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppPlayPvpRoute = AppPlayPvpRouteImport.update({
  id: '/pvp',
  path: '/pvp',
  getParentRoute: () => AppPlayRoute,
} as any)
const AppGamesStudiesRoute = AppGamesStudiesRouteImport.update({
  id: '/studies',
  path: '/studies',
  getParentRoute: () => AppGamesRoute,
} as any)
const AppGamesMyGamesRoute = AppGamesMyGamesRouteImport.update({
  id: '/my-games',
  path: '/my-games',
  getParentRoute: () => AppGamesRoute,
} as any)
const AppGamesImportedRoute = AppGamesImportedRouteImport.update({
  id: '/imported',
  path: '/imported',
  getParentRoute: () => AppGamesRoute,
} as any)
const AppAnalysisGameIdRoute = AppAnalysisGameIdRouteImport.update({
  id: '/analysis/$gameId',
  path: '/analysis/$gameId',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesStudiesStudyIdRoute = AppGamesStudiesStudyIdRouteImport.update({
  id: '/$studyId',
  path: '/$studyId',
  getParentRoute: () => AppGamesStudiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/tutorial': typeof TutorialRoute
  '/dashboard': typeof AppDashboardRoute
  '/games': typeof AppGamesRouteWithChildren
  '/import': typeof AppImportRoute
  '/play': typeof AppPlayRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/analysis/$gameId': typeof AppAnalysisGameIdRoute
  '/games/imported': typeof AppGamesImportedRoute
  '/games/my-games': typeof AppGamesMyGamesRoute
  '/games/studies': typeof AppGamesStudiesRouteWithChildren
  '/play/pvp': typeof AppPlayPvpRoute
  '/games/studies/$studyId': typeof AppGamesStudiesStudyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/tutorial': typeof TutorialRoute
  '/dashboard': typeof AppDashboardRoute
  '/games': typeof AppGamesRouteWithChildren
  '/import': typeof AppImportRoute
  '/play': typeof AppPlayRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/analysis/$gameId': typeof AppAnalysisGameIdRoute
  '/games/imported': typeof AppGamesImportedRoute
  '/games/my-games': typeof AppGamesMyGamesRoute
  '/games/studies': typeof AppGamesStudiesRouteWithChildren
  '/play/pvp': typeof AppPlayPvpRoute
  '/games/studies/$studyId': typeof AppGamesStudiesStudyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/about': typeof AboutRoute
  '/tutorial': typeof TutorialRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/games': typeof AppGamesRouteWithChildren
  '/_app/import': typeof AppImportRoute
  '/_app/play': typeof AppPlayRouteWithChildren
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/_app/analysis/$gameId': typeof AppAnalysisGameIdRoute
  '/_app/games/imported': typeof AppGamesImportedRoute
  '/_app/games/my-games': typeof AppGamesMyGamesRoute
  '/_app/games/studies': typeof AppGamesStudiesRouteWithChildren
  '/_app/play/pvp': typeof AppPlayPvpRoute
  '/_app/games/studies/$studyId': typeof AppGamesStudiesStudyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/tutorial'
    | '/dashboard'
    | '/games'
    | '/import'
    | '/play'
    | '/profile'
    | '/settings'
    | '/auth/login'
    | '/auth/signup'
    | '/analysis/$gameId'
    | '/games/imported'
    | '/games/my-games'
    | '/games/studies'
    | '/play/pvp'
    | '/games/studies/$studyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/tutorial'
    | '/dashboard'
    | '/games'
    | '/import'
    | '/play'
    | '/profile'
    | '/settings'
    | '/auth/login'
    | '/auth/signup'
    | '/analysis/$gameId'
    | '/games/imported'
    | '/games/my-games'
    | '/games/studies'
    | '/play/pvp'
    | '/games/studies/$studyId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/about'
    | '/tutorial'
    | '/_app/dashboard'
    | '/_app/games'
    | '/_app/import'
    | '/_app/play'
    | '/_app/profile'
    | '/_app/settings'
    | '/auth/login'
    | '/auth/signup'
    | '/_app/analysis/$gameId'
    | '/_app/games/imported'
    | '/_app/games/my-games'
    | '/_app/games/studies'
    | '/_app/play/pvp'
    | '/_app/games/studies/$studyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AboutRoute: typeof AboutRoute
  TutorialRoute: typeof TutorialRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutorial': {
      id: '/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof TutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/play': {
      id: '/_app/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof AppPlayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import': {
      id: '/_app/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/games': {
      id: '/_app/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof AppGamesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/play/pvp': {
      id: '/_app/play/pvp'
      path: '/pvp'
      fullPath: '/play/pvp'
      preLoaderRoute: typeof AppPlayPvpRouteImport
      parentRoute: typeof AppPlayRoute
    }
    '/_app/games/studies': {
      id: '/_app/games/studies'
      path: '/studies'
      fullPath: '/games/studies'
      preLoaderRoute: typeof AppGamesStudiesRouteImport
      parentRoute: typeof AppGamesRoute
    }
    '/_app/games/my-games': {
      id: '/_app/games/my-games'
      path: '/my-games'
      fullPath: '/games/my-games'
      preLoaderRoute: typeof AppGamesMyGamesRouteImport
      parentRoute: typeof AppGamesRoute
    }
    '/_app/games/imported': {
      id: '/_app/games/imported'
      path: '/imported'
      fullPath: '/games/imported'
      preLoaderRoute: typeof AppGamesImportedRouteImport
      parentRoute: typeof AppGamesRoute
    }
    '/_app/analysis/$gameId': {
      id: '/_app/analysis/$gameId'
      path: '/analysis/$gameId'
      fullPath: '/analysis/$gameId'
      preLoaderRoute: typeof AppAnalysisGameIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/games/studies/$studyId': {
      id: '/_app/games/studies/$studyId'
      path: '/$studyId'
      fullPath: '/games/studies/$studyId'
      preLoaderRoute: typeof AppGamesStudiesStudyIdRouteImport
      parentRoute: typeof AppGamesStudiesRoute
    }
  }
}

interface AppGamesStudiesRouteChildren {
  AppGamesStudiesStudyIdRoute: typeof AppGamesStudiesStudyIdRoute
}

const AppGamesStudiesRouteChildren: AppGamesStudiesRouteChildren = {
  AppGamesStudiesStudyIdRoute: AppGamesStudiesStudyIdRoute,
}

const AppGamesStudiesRouteWithChildren = AppGamesStudiesRoute._addFileChildren(
  AppGamesStudiesRouteChildren,
)

interface AppGamesRouteChildren {
  AppGamesImportedRoute: typeof AppGamesImportedRoute
  AppGamesMyGamesRoute: typeof AppGamesMyGamesRoute
  AppGamesStudiesRoute: typeof AppGamesStudiesRouteWithChildren
}

const AppGamesRouteChildren: AppGamesRouteChildren = {
  AppGamesImportedRoute: AppGamesImportedRoute,
  AppGamesMyGamesRoute: AppGamesMyGamesRoute,
  AppGamesStudiesRoute: AppGamesStudiesRouteWithChildren,
}

const AppGamesRouteWithChildren = AppGamesRoute._addFileChildren(
  AppGamesRouteChildren,
)

interface AppPlayRouteChildren {
  AppPlayPvpRoute: typeof AppPlayPvpRoute
}

const AppPlayRouteChildren: AppPlayRouteChildren = {
  AppPlayPvpRoute: AppPlayPvpRoute,
}

const AppPlayRouteWithChildren =
  AppPlayRoute._addFileChildren(AppPlayRouteChildren)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppGamesRoute: typeof AppGamesRouteWithChildren
  AppImportRoute: typeof AppImportRoute
  AppPlayRoute: typeof AppPlayRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppAnalysisGameIdRoute: typeof AppAnalysisGameIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppGamesRoute: AppGamesRouteWithChildren,
  AppImportRoute: AppImportRoute,
  AppPlayRoute: AppPlayRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppAnalysisGameIdRoute: AppAnalysisGameIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AboutRoute: AboutRoute,
  TutorialRoute: TutorialRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
